config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/users/:id/alarms' => 'users#alarms', as: :alarms
  delete 'logout' => 'sessions#destroy'
  get "/auth/:provider/callback" => "sessions#create"
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
    
#  has_secure_password
    # Returns the hash digest of the given string.
#  def User.digest(string)
#    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
#                                                  BCrypt::Engine.cost
#    BCrypt::Password.create(string, cost: cost)
#  end
    
    
    # Returns a random token.
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    # Remembers a user in the database for use in persistent sessions.
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, remember_token)
    end
    
    # Returns true if the given token matches the digest.
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        self.remember_digest == remember_token
#        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    # Forgets a user.
    def forget
        update_attribute(:remember_digest, nil)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
    
    
    private
        # Confirms a logged-in user.
    def logged_in_user
        unless logged_in?
#            store_location
            flash[:danger] = "Please log in."
            redirect_to root_path
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
        if current_user
            redirect_to current_user
        else
             #or whatever
        end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
    
  def create
    auth = request.env["omniauth.auth"]      
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    log_in user
    remember user
    redirect_to user

               
#      user = User.find_by(email: params[:session][:email].downcase)
#      if user && user.authenticate(params[:session][:password])
#        log_in user
#        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
#        remember user
#        redirect_to user
#      else
#        flash.now[:danger] = 'Invalid email/password combination'  
#        render 'new'
#      end
  end
    
  def destroy
    log_out if logged_in?
    session[:user_id] = nil
    flash[:success] = 'Signed out'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in_user, only: [:show, :create, :new]
    before_action :correct_user,   only: [:show]

  def show
    @user = User.find(params[:id])
  end
    
  def new
  end
    
  def create
  end
    
    private
    
# Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def full_title(page_title = ' ')
        base_title = "SweepAlert"
            if page_title.empty?
                base_title
            else
                page_title + " | " + base_title
            end
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end
    
  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
    
    def logged_in?
        !current_user.nil?
    end
    
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
    
    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end
    
      # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
    #Returns the Gravatar for the given user
#    def gravatar_for(user)
#        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
#        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
#    image_tag(gravatar_url, alt: user.name, class: "gravatar")
#    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
<!--MOBILE WEB APP OPTIMIZATION CODE-->
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="mobile-web-app-capable" content="yes">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,700' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<!--    <link rel="points" type="application/json" href="data.geojson">-->
    <%= csrf_meta_tags %>

</head>
    
<body class='<%= controller_name %> <%= action_name %>'>
    <div class="container">
        <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= image_tag("truck.png", class:"logo") %>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <% if logged_in? %>
                <li>
                <%= link_to "Log out", logout_path, method: "delete"%>
              </li>
              <% else %>
              <li><%= link_to "Log in with Gmail", "/auth/google_oauth2" %></li>
              <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
<%= yield %>  

    </div>

</body>
</html>

app/views/pages/home.html.erb
<div class="row splash">
    <div class="col-md-4 col-md-offset-4 col-xs-12 box">
        <div class="logos">Sweep Alert</div>
        <%= image_tag("truck.png", class:"truck col-xs-offset-4") %>    
        <div class="logos tagline">Avoid street sweeping tickets.</div>
    </div>
</div>

<div class="row ribbons height">
    <div class= "col-md-12 banner">
        <i class="fa fa-arrow-down fa-inverse animated bounce"></i>
        Add to homescreen
        <i class="fa fa-arrow-down fa-inverse animated bounce"></i>
    </div>
</div>

<div class="row ribbons">
    <!--DIRECTIONS INTRO RIBBON-->
    <div class= "col-md-12">
        <%= button_to "Log in with Gmail", "/auth/google_oauth2",class:"btn btn-primary btn-xl intro1" %>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<!--MAP-->
<div class="row">
    <div class ="map">
        <div id="map" class = "col-md-12"></div>
    </div>
</div>

<div class="row ribbons">
    <!--DIRECTIONS INTRO RIBBON-->
    <div class= "col-md-12 intro">
        <i class="fa fa-road fa-inverse fa-lg"></i> Click a street.
        <i class='fa fa-bell-o fa-lg'></i> Set a reminder.
    </div>
    
    <!--SET ALARM OPTIONS-->
    <div class= "col-md-12" id="setTime">
        <button class="btn setAlert" id="setTime1"></button>
        <button class="btn setAlert" id="setTime2"></button>
    </div>
    
    <!--CONFIRMATION OF GOOGLE EVENT CREATION RIBBON-->
    <div class= "col-md-12 setTime">
        <i class= "fa fa-calendar fa-lg"></i> Google reminder set.
    </div>
</div>

<script src="https://apis.google.com/js/client.js?onload=checkAuth"></script>







         